const messages: Record<string, string> = {
  voice_model_unsupported: '此模型尚未接入实时通话，请刷新模型列表后重新选择。',
  voice_model_unavailable: '所选通话模型已停用或缺少密钥，请检查模型管理中的通道配置后重试。',
  microphone_denied: '未获得麦克风权限。请在浏览器网站设置中允许麦克风，再重试。',
  microphone_missing: '未找到可用麦克风。请连接或启用麦克风后重试。',
  microphone_unavailable: '无法使用麦克风。请检查系统权限、设备连接或其他应用是否正在占用，再重试。',
  microphone_failed: '麦克风启动失败。请检查设备和系统权限后重试。',
  audio_initialization_failed: '音频引擎启动失败。请重新开始通话；若仍失败，请刷新页面后重试。',
  audio_processing_failed: '音频处理模块未能正常工作，通话已停止。请刷新页面后重试。',
  audio_protocol_failed: '收到的语音数据无法处理，通话已停止。请重新开始通话。',
  connection_failed: '语音连接失败。请检查网络后重试。',
  connection_closed: '语音连接已断开。请重新开始通话。',
  connection_slow: '语音发送积压，已停止通话。请检查网络后重试。',
  auth_timeout: '通话身份校验超时。请重新开始；若仍失败，请重新登录。',
  connection_expired: '通话连接未能保持有效。请重新开始；若仍失败，请检查网络和登录状态。',
  provider_timeout: '等待语音服务响应超时。请稍后重试，文字聊天不受影响。',
  provider_connection_failed: '未能连接语音服务。请稍后重试，文字聊天不受影响。',
  provider_disconnected: '语音服务连接已断开。请重新开始通话。',
  provider_request_failed: '语音服务未能处理本次请求。请重新开始；若再次中断，请反馈发生时的操作。',
  provider_protocol_failed: '语音服务返回的数据无法处理。请重新开始；若仍失败，请反馈此提示。',
  provider_frame_limit: '语音服务返回的数据超出处理上限。请重新开始通话。',
  slow_client: '接收语音出现积压，通话已结束。请检查网络后重试。',
  slow_provider: '向语音服务发送数据出现积压。请稍后重试，文字聊天不受影响。',
  secure_context_required: '请用 HTTPS 域名打开元枢后再通话。',
  audio_not_supported: '此浏览器不支持实时音频，请使用新版 Chrome 或 Safari。',
  audio_interrupted: '手机中断了音频，通话已结束。回到页面后可重新开始。',
  microphone_disconnected: '麦克风已断开，请检查设备后重新开始。',
  unauthorized: '登录已失效，请重新登录后再开始。',
  conversation_gone: '当前聊天已不存在，请选择一个聊天后再开始。',
  conversation_changed: '已切换聊天，通话已结束。',
  call_busy: '已有通话或录音占用音频，请先结束后再试。',
  rate_limit: '尝试过于频繁，请稍等一分钟再试。',
  call_time_limit: '本次通话已到 25 分钟上限，可以重新开始。',
  provider_unavailable: '实时语音通道未配置，请先配置阶跃通道。',
  same_origin_required: '请直接打开元枢服务的 HTTPS 域名进行通话。',
}
const timeouts: Record<string, string> = {
  microphone: '等待麦克风授权超时。请查看浏览器或系统权限提示，再重新开始。',
  audio: '准备音频超时。请重新开始通话；若仍失败，请刷新页面后重试。',
  session: '准备当前会话超时。请返回聊天确认会话可用后重试。',
  ticket: '获取通话凭证超时。请检查登录状态与网络后重试。',
  socket: '建立语音连接超时。请检查网络后重试。',
  service: '等待语音服务就绪超时。请稍后重试，文字聊天不受影响。',
}
export const callError = (code?: string, failureStage?: string | null) => code === 'connection_timeout'
  ? timeouts[failureStage || ''] || '通话准备超时。请重新开始。'
  : code ? messages[code] || '通话已停止。请重新开始；文字聊天不受影响。' : ''
