param([switch]$ResumePackaging)
$ErrorActionPreference = 'Stop'
# 环境重名清理（2026-09-18 真机排查）：Windows 里 HTTP_PROXY 和 http_proxy 是同一个键，
# 但环境块里可能两份都在（本机都是 http://127.0.0.1:7890）→ PowerShell 5.1 的 Start-Process
# 复制环境时抛 "Item has already been added. Key: 'HTTP_PROXY' / Key being added: 'http_proxy'"，
# 表现就是"双击跑了、但一两秒就退出，什么都没发生"。统一只留大写一份再往下走。
foreach ($pair in @(@('http_proxy', 'HTTP_PROXY'), @('https_proxy', 'HTTPS_PROXY'), @('no_proxy', 'NO_PROXY'))) {
  $lowerVal = [Environment]::GetEnvironmentVariable($pair[0], 'Process')
  $upperVal = [Environment]::GetEnvironmentVariable($pair[1], 'Process')
  try { Remove-Item -LiteralPath "Env:$($pair[0])" -ErrorAction SilentlyContinue } catch {}
  if (-not $upperVal -and $lowerVal) { [Environment]::SetEnvironmentVariable($pair[1], $lowerVal, 'Process') }
}
$dir = $PSScriptRoot
$workspaceRoot = if ($env:PI_WORKSPACE) { $env:PI_WORKSPACE } else { 'D:\pi-workspace' }
$cacheRoot = Join-Path $workspaceRoot '.build-cache'
$rustBin = Join-Path ([Environment]::GetFolderPath('UserProfile')) '.cargo\bin'
$env:Path = $rustBin + ';' + $env:Path
$env:ANDROID_HOME = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { 'C:\Android\Sdk' }
$env:NDK_HOME = if ($env:NDK_HOME) { $env:NDK_HOME } else { Join-Path $env:ANDROID_HOME 'ndk\27.0.12077973' }
$env:CARGO_HOME = Join-Path $cacheRoot 'cargo-home'
$env:CARGO_TARGET_DIR = Join-Path $cacheRoot 'cargo'
$env:GRADLE_USER_HOME = Join-Path $cacheRoot 'gradle'
$env:npm_config_cache = Join-Path $cacheRoot 'npm'
$env:TEMP = Join-Path $cacheRoot 'tmp'
$env:TMP = $env:TEMP
$env:CARGO_TERM_COLOR = 'never'
$log = Join-Path $dir 'android-build-024.log'
$errorLog = Join-Path $dir 'android-build-024-stderr.log'
$exitFile = Join-Path $dir 'android-build.exit'
$code = 1
try {
  # ── 版本号同步（2026-09-20 修）────────────────────────────────────────────
  # tauri.properties 是 `tauri android init` 生成的，而 `tauri android build` **不会重写它**。
  # 后果：仓库升到 2.109.3，打出来的 APK 内部仍自称 2.108.0。真机核对：
  #   aapt2 dump badging 元枢-v2.109.0-arm64.apk → versionName='2.108.0' versionCode='2108000'
  # 文件名与 APK 自称的版本对不上；安卓靠 versionCode 判更新，这个错会卡住覆盖安装。
  # 构建前按仓库根 version.json 重写一次（该文件头本来就写明是自动生成的）。
  $versionJson = Join-Path (Split-Path $dir -Parent) 'version.json'
  if (Test-Path -LiteralPath $versionJson) {
    $v = (Get-Content -LiteralPath $versionJson -Raw | ConvertFrom-Json).version
    $parts = "$v".Split('.')
    if ($parts.Count -eq 3) {
      $vcode = [int]$parts[0] * 1000000 + [int]$parts[1] * 1000 + [int]$parts[2]
      $propsFile = Join-Path $dir 'src-tauri\gen\android\app\tauri.properties'
      $props = @(
        '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
        "tauri.android.versionName=$v",
        "tauri.android.versionCode=$vcode"
      ) -join "`n"
      $old = if (Test-Path -LiteralPath $propsFile) { (Get-Content -LiteralPath $propsFile -Raw) } else { '' }
      if ($old.Trim() -ne $props.Trim()) {
        [IO.File]::WriteAllText($propsFile, $props + "`n", (New-Object System.Text.UTF8Encoding($false)))
        Write-Host "[版本同步] tauri.properties 已按 version.json 重写为 $v (versionCode=$vcode)"
      }
    }
  }
  New-Item -ItemType Directory -Force -Path $env:CARGO_HOME, $env:CARGO_TARGET_DIR, $env:GRADLE_USER_HOME, $env:TEMP | Out-Null
  if (-not $ResumePackaging) {
    $build = Start-Process -FilePath $env:ComSpec -ArgumentList @('/d', '/s', '/c', '"".\node_modules\.bin\tauri.cmd" android build --target aarch64 --apk --ci"') -WorkingDirectory $dir -NoNewWindow -PassThru -RedirectStandardOutput $log -RedirectStandardError $errorLog
    $null = $build.Handle
    $build.WaitForExit()
    $code = $build.ExitCode
  }
  $buildMessages = Get-Content -LiteralPath $errorLog -Raw
  $buildMessages = [regex]::Replace($buildMessages, ([char]27 + '\[[0-9;]*m'), '')
  if ($code -ne 0 -and $buildMessages.Contains('Creation symbolic link is not allowed') -and $buildMessages.Contains('Finished `release` profile')) {
    # Rust compilation succeeded. Windows without symlink privilege can package a verified copy instead.
    $nativeLib = Join-Path $env:CARGO_TARGET_DIR 'aarch64-linux-android\release\libyuanshu_lib.so'
    $androidDir = Join-Path $dir 'src-tauri\gen\android'
    $jniDir = Join-Path $androidDir 'app\src\main\jniLibs\arm64-v8a'
    $jniLib = Join-Path $jniDir 'libyuanshu_lib.so'
    if (-not (Test-Path -LiteralPath $nativeLib) -or (Get-Item -LiteralPath $nativeLib).Length -eq 0) { throw 'Compiled Android library is missing.' }
    if ((Test-Path -LiteralPath $jniLib) -and ((Get-Item -LiteralPath $jniLib).Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Unexpected existing JNI symlink; inspect before replacing.' }
    New-Item -ItemType Directory -Force -Path $jniDir | Out-Null
    Copy-Item -LiteralPath $nativeLib -Destination $jniLib -Force
    $gradleLog = Join-Path $dir 'android-gradle-024.log'
    $gradleErrorLog = Join-Path $dir 'android-gradle-024-stderr.log'
    $gradle = Start-Process -FilePath $env:ComSpec -ArgumentList @('/d', '/s', '/c', '"".\gradlew.bat" --no-daemon assembleArm64Release testArm64ReleaseUnitTest -x rustBuildArm64Release"') -WorkingDirectory $androidDir -NoNewWindow -PassThru -RedirectStandardOutput $gradleLog -RedirectStandardError $gradleErrorLog
    $null = $gradle.Handle
    $gradle.WaitForExit()
    $code = $gradle.ExitCode
  }
} catch {
  $_ | Out-File -LiteralPath $log -Append -Encoding utf8
} finally {
  [IO.File]::WriteAllText($exitFile, $code.ToString())
}
exit $code
